apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: springother
  name: springboot-init
  labels:
    app: springboot-init
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-init
  template:
    metadata:
      labels:
        app: springboot-init
    spec:
      containers:
        - name: springboot-init
          image: ccr.ccs.tencentyun.com/xxxxxxxxxxxxx/springbootinit:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            periodSeconds: 10
            initialDelaySeconds: 3
            terminationGracePeriodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10