---
apiVersion: v1
kind: Service
metadata:
  name: springbootgatewayserviceprovider
  namespace: springgateway
  labels:
    app: springboot-gateway-serviceprovider
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: springboot-gateway-serviceprovider