apiVersion: v1
kind: Service
metadata:
  name: springbootclient
  namespace: spring
  labels:
    app: springboot-client
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: springboot-client